### ISSUE TITLE
LC Public vs LC Member Data

### ISSUE THREAD

**Issue by Predacity** [kuhnrl30/LendingClubData#1]
Ryan, the LC loan data files available to the public don't have FICO scores and some other useful variables.  When you log in to your account, on the other hand, and download those data files as a member, you will see a few more columns added.  In this package you are building, are you trying to get the public data only?

**Comment by kuhnrl30** [comment]
I agree that the member data would be more useful.  It's a challenge to script the download because LC is using signed URL's- I'll have to look into a work around but I'm not getting my hopes up.  I'll manually download for the Q1 update later this week.
